### ISSUE TITLE
segment-wise beautification

### ISSUE THREAD

**Issue by tobiaskauer** [tkauer/facelift#1]
to create progressively increasing beautification scenarions, i am thinking about step-by-step unlocking more segments (with initially most of it blocked):

0. Input Image
1. lock everything but trees
2. unlock Mobility (Pedestrians, Cycles, Vehicles)
3. unlock Side of Road (Pavement, Fences, Poles, Sign Symbols)
4. unlock Road (Road Marking, Roads)
5. unlock Buildings
6. unlock Sky

**Comment by tobiaskauer** [comment]
other (discarded) ideas for progress within segments:

**CHEAP TO EXPENSIVE (very subjective):**
Pedestrians
Cycles
Vehicles
Fences
Trees
Road Marking
Sign Symbols
Poles
Pavement
Roads
Buildings
(Sky? Does not really fit)

**Based on Activation of Output (data-based, slide 68):**
Building
Sky
Roadmarking
Road
Vehicle
Pedestrian
Bike
Pole
Signsymbol
Tree

**Comment by sagarjoglekar** [comment]
I am adding images as i get them, please check out htis folder :https://www.dropbox.com/sh/ulxasdevsyu23we/AAC4zx_TCiXfh2P4dfFYKQv0a?dl=0
Originals are the orginal samples , random , some are borderline just to see what the pipeline does, 
In the folder lockdowns, I am creating folders as per the locking segments prescribed above

**Comment by sagarjoglekar** [comment]
Example 831, 59 and 42 are weirdcases, 831 and 49 are borderline, which means they fall somewhere on the edge of beauty threshold for which the algorithm is trained for, so they give some weird results, 43 is a picture of an ugly wall.

**Comment by tobiaskauer** [comment]
grid for 15
![grid_15](https://user-images.githubusercontent.com/28626912/31722749-d0f5da02-b414-11e7-84f6-aa2f01ffceb6.jpg)

**Comment by tobiaskauer** [comment]
grid for 56
![grid_56](https://user-images.githubusercontent.com/28626912/31722773-e09fbcf2-b414-11e7-80fa-b167358bec91.jpg)

**Comment by tobiaskauer** [comment]
grid for 111
![grid_111](https://user-images.githubusercontent.com/28626912/31723005-8c8358bc-b415-11e7-8444-a13deed48d75.jpg)

**Comment by tobiaskauer** [comment]
grid for 158
![grid_158](https://user-images.githubusercontent.com/28626912/31723629-5300fdd6-b417-11e7-8b2e-96195f7d7813.jpg)

**Comment by tobiaskauer** [comment]
analysis of 158
![158_analysis](https://user-images.githubusercontent.com/28626912/31732623-0d114f6e-b431-11e7-9d5b-8213131e42b8.jpg)

**Comment by tobiaskauer** [comment]
closed: we will drop that idea for now and just compare the ugly version with one single beautiful alternative. 

for this one more beautiful alternative, i am not sure, whether blocking any segments will help the explanation pipeline - if that is not the case: no holds barred!
