### ISSUE TITLE
Granularity / Spread of Input Dataset

### ISSUE THREAD

**Issue by tobiaskauer** [tkauer/facelift#4]
**Questions:**
- How many locations are in the two biggest datasets (from my knowledgeNY / Boston)
- Where are they?
- Can we generate beautified scenarios (six scenarios, each with a realistic image, labels and calulated metrics) for each of these locations?

**Comment by tobiaskauer** [comment]
@sagarjoglekar Can you also give me the geolocations for the input and the output images?

**Comment by sagarjoglekar** [comment]
Boston Results : https://www.dropbox.com/s/tg4tvqrk8c5wcjp/BostonMatches.tar?dl=0

**Comment by tobiaskauer** [comment]
closed.
for boston we have:
- ~1,3k locations with a trueskill score, of which
- ~800 have labels (this will maybe grow to the full 1.3k), of which
- 130 have a more beautiful alternative
